### ISSUE TITLE
Add configuration (like colors)?

### ISSUE THREAD

**Issue by deeplook** [nschloe/tiptop#104]
Some of the chosen default colors for the text like darbblue are hard to read on a black background, which raises the question if these colors, or anything in fact, could be configured with whatever mechanism?

**Comment by nschloe** [comment]
tiptop just takes the colors from your terminal. If you find some things hard to read in tiptop, they'll probably be hard to read in other places as well. Best adapt your terminal color scheme?

**Comment by deeplook** [comment]
Looking at the code I see that color names are hardwired so it would appear at least somewhat unnatural to redefine those colors in a terminal in order to use customized colors. But I understand that from a development point this is an easy position to take. ;-)

**Comment by nschloe** [comment]
If more people are interested in this, I'll consider it. Closing until then.
