### ISSUE TITLE
ModuleNotFoundError: No module named 'termios'

### ISSUE THREAD

**Issue by markmbaum** [nschloe/tiptop#14]
After a successful `pip install tiptop`, running `tiptop` encoutered `ModuleNotFoundError: No module named 'termios'`. I tried installing `termios` via `pip install` and `conda install` but neither found a distribution. I'm on windows.

**Comment by nschloe** [comment]
Dup of https://github.com/nschloe/tiptop/issues/12.

**Comment by nschloe** [comment]
FYI, Windows is now supported.
