### ISSUE TITLE
Feature Request: Theming!

### ISSUE THREAD

**Issue by skamansam** [nschloe/tiptop#36]
In my terminal, the blue is hard to read, and I would very much like to be able to specify the colors via a config file. (This is an awesome project, btw!)

![image](https://user-images.githubusercontent.com/102971/143043734-d326f04e-bb49-4448-adb7-5e396a9c334b.png)

**Comment by nschloe** [comment]
Perhaps tiptop will get config options in the future. For now, the only way to adapt the colors is to adapt your terminal colors. Given that blue is illegible on your machine, perhaps that's a good idea anyway.

**Comment by nschloe** [comment]
I think I'll close this one. Theming is probably out-of-reach for tiptop right now, and the actual bug here is that your terminal blue is just not legible on the dark background. The terminal theme should be fixed instead.
