### ISSUE TITLE
Feature: Flag for those who use white background terminal

### ISSUE THREAD

**Issue by DarrenPIngram** [nschloe/tiptop#45]
I use a white background terminal (it is easier on my eyes as visually impaired). Could there be a flag/config option so it inverts the colours used? At least on my Mac a lot of the stuff is not displayed with a white background.

This is what I see:

![f](https://user-images.githubusercontent.com/181628/145677604-6e70e96e-840c-4f8c-b878-a58a53004abf.png)

**Comment by nschloe** [comment]
There was a similar request a while ago asking for _theming_, and I turned down that request. My reasoning was that if you can't see something clearly, then probably you should adapt your terminal color scheme.

Do I understand correctly that you want a dark background for tiptop, but a white background for everything else? Wouldn't that result in you not being able to see much of what's displayed in tiptop?

**Comment by DarrenPIngram** [comment]
Hi. Maybe my case is more unique due to my VI.

I am not sure of the technicalities, but if it was possible for the text
displayed (which is light text on a dark background) could be (by command
or config) be changed to use a dark text that can be seen on a white
background) that would be good.

I do accept that most people use a dark background. Indeed that is what I
used to use in the days of green and orange terminals pre-PC)

Certainly I am not requesting in any case "deep customisation" and theming
per se. Just an invert or "change white to back" (or similar) option if
implementing such would be a relatively easy and quick fix for you. Quick
as in use of your time. I am not trying to "demand" a fast response for any
action you might be able to provide!

**Comment by nschloe** [comment]
I understand a white background is good in regular terminal operation for your visual needs. What's wrong with tiptop having a white background? When switching to a dark theme, wouldn't you have a hard time seeing what's displayed?

**Comment by DarrenPIngram** [comment]
I've no problem with Tiptop having a white background. As I run it now, with a white background, a lot of the information doesn't display (as shown in the screenshot earlier). I don't use dark themes ever (unless forced to) because on the whole the contrast between black / dark greys and the lighter characters is hard to read, especially with certain fonts and sizes.

HTH.

**Comment by nschloe** [comment]
> a lot of the information doesn't display 

I haven't seen that. The screenshot looks okay. What's missing?

**Comment by DarrenPIngram** [comment]
Ah, oops, hmm, this is embarassing.

When I had ran tiptop several times I did not see the graph in the top part of the screen be displayed. I had not let it run long enough to start populating and, despite it showing in the screen shot, I didn't see it :( It took someone else to point it out to me. Sorry for the false alert.

Now, whilst looking intensely at the screen, for some reason my Mac thinks the fw0 network port should be viewed as the default for tiptop (despite never using it). I can display the ethernet port activity with --net en0 but is there a way to make this the default (even if I have to be told where to edit the code, if that is possible?

**Comment by nschloe** [comment]
> Sorry for the false alert.

Problem solved. :)

> can display the ethernet port activity with --net en0 but is there a way to make this the default (even if I have to be told where to edit the code, if that is possible?

tiptop tries to be smart in picking the "correct" network interface, e.g. it skips `docker*` and `lo*`, and tries to use an interface that is `up`. Sometimes, this logic fails, which is why there is the command-line switch. The logic for it is [here](https://github.com/nschloe/tiptop/blob/main/src/tiptop/_net.py#L18).

I've just added a discount for `fw` interfaces, perhaps that'll already do it for you.

**Comment by DarrenPIngram** [comment]
Thanks. I can try it. Does it take a time for the release (I see it on
Github) to appear in the repository when you enter pip install tiptop ? I
couldn't see a way to force it to download the 0.16 version, but I am not
that experienced with forcing Github downloads either.

**Comment by nschloe** [comment]
It should be immediately available. You can try
```
pip install tiptop --force
```

**Comment by DarrenPIngram** [comment]
That worked. A bit more knowledge for the day too. Thank you! The network
was happy without the --net flag needing to be deployed.

**Comment by nschloe** [comment]
You're welcome!
