### ISSUE TITLE
Black screen after start

### ISSUE THREAD

**Issue by ArneBachmannDLR** [nschloe/tiptop#58]
Hi, Windows 10 (19042.1466) in an Enterprise setup, using Mambaforge with a Python 3.9 virtual environment.
Starting `tiptop` clears the console and shows a blinking half-caret cursor in the lower right corner. Nothing else happens.

Is there a way to debug this situation? I would like to help.

**Comment by nschloe** [comment]
You can use
```
tiptop --log tiptop.log
```
and post the log here.

**Comment by ArneBachmannDLR** [comment]
Ok, you've been busy! Not only was I missing the log function, but it also works now!
```
tiptop --log D:\tiptop.log
usage: tiptop [-h] [--version] [--net NET]
```
After `pip install -U tiptop` from 1.3 to 1.5 it works now.
