### ISSUE TITLE
temperature unavailable on macOS

### ISSUE THREAD

**Issue by jkbecker** [nschloe/tiptop#6]
Hi! This looks like a nice little tool, I discovered earlier when @willmcgugan retweeted your announcement.

I just tried running it on macOS and ran into a couple issues (PR with quick fixes incoming), but one of them seems to be bigger than the rest, which is the butchered temperature situation on macOS.

This is a known problem (see [this](https://stackoverflow.com/questions/2440511/getting-cpu-temperature-using-python) and [this](https://www.reddit.com/r/learnpython/comments/bjulew/mac_os_get_cpu_temp_with_python/) for a non-exhaustive description of the issue, but it comes down to `psutil.sensors_temperatures()` being unavailable in the macOS version of the `psutil` package, which trips over the following line:

https://github.com/nschloe/tiptop/blob/76d3f299988881c352fc7bc3c4b90cb32ac399d1/src/tiptop/_cpu.py#L56

I am adding a quick fix for now but since the temp graph in tiptop is so neat it would probably be worth the effort to find a functionally usable workaround for this as well.

**Comment by nschloe** [comment]
The temperature thing has been fixed.
