### ISSUE TITLE
suppress creation of textual.log

### ISSUE THREAD

**Issue by amorfinv** [nschloe/tiptop#61]
Hello,

Really cool app. 

Is it possible to suppress the creation of ```textual.log``` when running tiptop?

![image](https://user-images.githubusercontent.com/78442543/154837910-73e04741-af24-4256-9845-d27f383c2919.png)

thank you,
Andres

**Comment by nschloe** [comment]
Fixed in 0.1.5. Thanks for the report!

**Comment by amorfinv** [comment]
thanks!.. upgraded to 0.1.5
