### ISSUE TITLE
Tiptop writes over a part of the screen history

### ISSUE THREAD

**Issue by ArneBachmannDLR** [nschloe/tiptop#63]
On Windows' `cmd.exe` a part of the terminal lines buffer is written over when exiting tiptop.

This happened when I quit tiptop via Ctrl+C: I can only see commands from around 30 lines up/ago, but no the ones just before starting titop, as the screen buffer wasn't restored when quitting tiptop.

Same with hitting `q`, only the cursor is now at the top not at the bottom.

**Comment by nschloe** [comment]
That's probably [textual](https://github.com/Textualize/textual) issue, tiptop itself doesn't mess with the buffer.
