### ISSUE TITLE
Error when press 'q' to quit.

### ISSUE THREAD

**Issue by victorqribeiro** [nschloe/tiptop#79]
After pressing Q to exit I got the following screen:

![image](https://user-images.githubusercontent.com/3822139/157582459-9ffc0899-e5d4-48ed-a556-24e503955451.png)

Ubuntu x64 5.13.0-35-generic

**Comment by nschloe** [comment]
Interesting. Looks like the disk_io_counters don't work for you. Screenshot of the running app?
